version: "3"

services:
        mon_app:
                image: monimage
                depends_on:
                        - redis
                ports:
                        - "800:80"
        redis:
                image: redis
                ports:
                        - "6379:6379"



